# Dependencies
markdown: redcarpet

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CodingHighway
tagline:          A Computer Science blog
url:              http://www.codinghighway.com
paginate:         1
baseurl:          /
author:
  name:           Filipe Goncalves
  url:            https://github.com/filipegoncalves
  email:          filipe@codinghighway.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/filipegoncalves/filipegoncalves.github.io

# List of pages to include in the header of the website.
pages_list: {'Archive':'/archive','About':'/about','Feed':'/atom.xml'}

# Needed for travis-ci. See http://jekyllrb.com/docs/continuous-integration/
exclude: [vendor]
