markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# markdown: KramdownPygments
# kramdown:
#  math_engine: mathjax
#  input: GFM
#  default_lang: c


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CodingHighway
# tagline:          A Computer Science blog
url:              http://www.codinghighway.com
paginate:         1
baseurl:          /
assets:		  assets/
author:
  name:           Filipe Goncalves
  url:            https://github.com/filipegoncalves
  email:          filipe@codinghighway.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/filipegoncalves/filipegoncalves.github.io

# List of pages to include in the header of the website.
pages_list: {'Archive':'/archive','Books':'/techbooks','Resume':'/resume','About':'/about'}

# Needed for travis-ci. See http://jekyllrb.com/docs/continuous-integration/
exclude: [vendor]
